### ISSUE TITLE
Does this support zones?

### ISSUE THREAD

**Issue by gcstang** [owlwalks/rind#1]
Great project!

Thank you

I'd like to convert from using bind in my small private network to this if possible.

(It's possible I'm making this more complicated than need be but if there is an alternative, please say so)

I'm currently using bind on a docker container with different zones configured.
Some zones point to their local file and others are forwarded to for example Cloudflare 1.1.1.1
Two different types of zones master and forward.
i.e.
`zone "knock.mydomain.com" {
        type master;
        file "/var/lib/bind/knock.mydomain.com.hosts";
};`

`zone "r.mydomain.com" {
        type forward;
        forwarders {
                1.1.1.1;
                };
        };`

master file file contents:
`$ttl 38400
knock.mydomain.com. IN      SOA     ns.mydomain.com. admin.gmail.com. (
                        1481752870
                        10800
                        3600
                        604800
                        38400 )

knock.mydomain.com.       IN      NS      ns.mydomain.com.
knock.mydomain.com. IN      A       192.168.2.112`

**Comment by owlwalks** [comment]
hi gcstang, at the moment it doesn't support zone file, the records are simply stored in binary (gob), it's a good feature to add though.

but we can make rind kinda works the same way, for rind, all queries will be forwarded by default, so i wouldn't worry for "r.mydomain.com."

for "knock.mydomain.com.", to point it to "192.168.2.112", we just need this:
```shell
// TTL 0 or 1 means rind will point "knock.mydomain.com." to 192.168.2.112 forever, until you curl -X DELETE it
curl -X POST \
  http://localhost/dns \
  -H 'Content-Type: application/json' \
  -d '{
	"Host": "knock.mydomain.com.",
	"TTL": 1,
	"Type": "A",
	"Data": "192.168.2.112"
}'
```

i will leave out SOA and NS record for your particular use, SOA is mainly for zone transfer (propagating records to secondary dns servers), and rind is not exactly an authoritative nameserver, so NS record doesn't really matter.

**Comment by gcstang** [comment]
Thank you for your response, I'll give it a shot.

**Comment by gcstang** [comment]
Is reverse lookup supported?

**Comment by owlwalks** [comment]
you can try dig -x after adding a PTR record, it should work

**Comment by owlwalks** [comment]
Closed to cover these use cases in README for future references

**Comment by gcstang** [comment]
Would you have a sample?
